# Generated by scripts/curate_models.py — the scraper imports this in
# preference to its built-in default. Regenerate rather than hand-edit.
MODELS = {
    "chevrolet_matiz": "https://avtoelon.uz/avto/chevrolet/matiz/",  # 1,939 listings
    "chevrolet_nexia2": "https://avtoelon.uz/avto/chevrolet/nexia2/",  # 1,784 listings
    "daewoo_nexia": "https://avtoelon.uz/avto/daewoo/nexia/",  # 997 listings
    "chevrolet_tracker_2": "https://avtoelon.uz/avto/chevrolet/tracker-2/",  # 923 listings
    "chevrolet_labo": "https://avtoelon.uz/avto/chevrolet/labo/",  # 872 listings
    "chevrolet_captiva": "https://avtoelon.uz/avto/chevrolet/captiva/",  # 661 listings
    "chevrolet_malibu2": "https://avtoelon.uz/avto/chevrolet/malibu2/",  # 596 listings
    "chevrolet_onix": "https://avtoelon.uz/avto/chevrolet/onix/",  # 509 listings
    "vaz_2106": "https://avtoelon.uz/avto/vaz/2106/",  # 440 listings
    "daewoo_tico": "https://avtoelon.uz/avto/daewoo/tico/",  # 347 listings
    "chevrolet_tracker": "https://avtoelon.uz/avto/chevrolet/tracker/",  # 298 listings
    "vaz_2107": "https://avtoelon.uz/avto/vaz/2107/",  # 294 listings
    "chevrolet_malibu": "https://avtoelon.uz/avto/chevrolet/malibu/",  # 257 listings
    "chevrolet_equinox": "https://avtoelon.uz/avto/chevrolet/equinox/",  # 223 listings
    "kia_k_5": "https://avtoelon.uz/avto/kia/k-5/",  # 203 listings
    "kia_sonet": "https://avtoelon.uz/avto/kia/sonet/",  # 161 listings
    "vaz_vesta": "https://avtoelon.uz/avto/vaz/vesta/",  # 160 listings
    "chevrolet_monza": "https://avtoelon.uz/avto/chevrolet/monza/",  # 156 listings
    "chevrolet_epica": "https://avtoelon.uz/avto/chevrolet/epica/",  # 148 listings
    "vaz_2121": "https://avtoelon.uz/avto/vaz/2121/",  # 127 listings
    "byd_chazor": "https://avtoelon.uz/avto/byd/chazor/",  # 118 listings
    "kia_sorento": "https://avtoelon.uz/avto/kia/sorento/",  # 116 listings
    "chery_tiggo_7_pro": "https://avtoelon.uz/avto/chery/tiggo-7-pro/",  # 112 listings
    "chery_arrizo_6_pro": "https://avtoelon.uz/avto/chery/arrizo-6-pro/",  # 104 listings
    "byd_song_plus_dm_i_champion": "https://avtoelon.uz/avto/byd/song-plus-dm-i-champion/",  # 102 listings
    "vaz_lada_r90": "https://avtoelon.uz/avto/vaz/lada-r90/",  # 100 listings
}

MODEL_KEYWORDS = {
    "chevrolet_matiz": ('matiz', 'матиз'),
    "chevrolet_nexia2": ('nexia 2', 'nexia2', 'нексия', 'нексия 2'),
    "daewoo_nexia": ('nexia', 'нексия'),
    "chevrolet_tracker_2": ('tracker 2', 'tracker2', 'трекер', 'трекер 2', 'трэкер', 'трэкер 2'),
    "chevrolet_labo": ('labo', 'лабо'),
    "chevrolet_captiva": ('captiva', 'каптива'),
    "chevrolet_malibu2": ('malibu', 'malibu 2', 'malibu2', 'малибу'),
    "chevrolet_onix": ('onix', 'оникс'),
    "vaz_2106": ('2106',),
    "daewoo_tico": ('tico', 'тико'),
    "chevrolet_tracker": ('tracker', 'трекер', 'трэкер'),
    "vaz_2107": ('2107',),
    "chevrolet_malibu": ('malibu', 'малибу'),
    "chevrolet_equinox": ('equinox', 'эквинокс'),
    "kia_k_5": ('k 5', 'k5', 'к-5', 'к5'),
    "kia_sonet": ('sonet', 'сонет'),
    "vaz_vesta": ('vesta', 'веста'),
    "chevrolet_monza": ('monza', 'монза'),
    "chevrolet_epica": ('epica', 'эпика'),
    "vaz_2121": ('2121',),
    "byd_chazor": ('chazor', 'чазор'),
    "kia_sorento": ('sorento', 'соренто'),
    "chery_tiggo_7_pro": ('tiggo 7 pro', 'tiggo7pro', 'тигго'),
    "chery_arrizo_6_pro": ('arrizo 6 pro', 'arrizo6pro', 'аризо', 'арризо'),
    "byd_song_plus_dm_i_champion": ('song', 'song plus', 'song plus dm i champion', 'songplusdmichampion', 'сонг'),
    "vaz_lada_r90": ('lada r90', 'ladar90', 'largus', 'r90', 'ларгус'),
}
